services:
  english_learning_server:
    build: .
    ports:
      - "5000:5000"
    networks:
      - english_network
    volumes:
      - redis_data1:/data

  english_redis:
    image: redis:latest
    networks:
      - english_network
    volumes:
      - redis_data1:/data

networks:
  english_network:

volumes:
  redis_data1:
